---
name: publish package

on:
  push:
    tags:
      - "v*.*.*"
      - "*.*.*"
    paths-ignore:
      - .github/**

jobs:
  publish:
    name: publish package
    uses: strg-at/github-workflows/.github/workflows/npm-publish.yaml@ae16851644aa20761762716e874cebdf811fbd40 # v2.1.4
    with:
      runner: '["ubuntu-latest"]'
