---
name: publish package

on:
  push:
    tags:
      - "v*.*.*"
      - "*.*.*"
    paths-ignore:
      - .github/**

jobs:
  publish:
    name: publish package
    uses: strg-at/github-workflows/.github/workflows/npm-publish.yaml@5b3a9b6c732a6dfd741d44588af89ba292318723 # v2.1.7
    with:
      runner: '["ubuntu-latest"]'
