---
name: publish package

on:
  push:
    tags:
      - "v*.*.*"
      - "*.*.*"
    paths-ignore:
      - .github/**

jobs:
  publish:
    name: publish package
    uses: strg-at/github-workflows/.github/workflows/npm-publish.yaml@2eccb26cd19da1d8aa15df7402c9d29251a8589b # v2.1.5
    with:
      runner: '["ubuntu-latest"]'
